# Generated by Django 3.0.1 on 2020-01-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='PhoneBodyColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebody_color_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'phonebody_colors',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetype_name', models.CharField(max_length=500)),
                ('vendor_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'phone_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customed', models.NullBooleanField()),
                ('custom_option', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Artist')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Item')),
                ('phonetype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PhoneType')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='RegularProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color_id', models.PositiveSmallIntegerField(null=True)),
                ('product_color_name', models.CharField(max_length=500, null=True)),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('imgae_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('phonebody_color_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PhoneBodyColor')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'regualr_product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(null=True)),
                ('comment_title', models.CharField(max_length=500, null=True)),
                ('comment_text', models.CharField(max_length=500, null=True)),
                ('is_buyer', models.NullBooleanField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'product_reviews',
            },
        ),
        migrations.AddField(
            model_name='phonebodycolor',
            name='phonetype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PhoneType'),
        ),
        migrations.CreateModel(
            name='CustomProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color_id', models.PositiveSmallIntegerField(null=True)),
                ('product_color_name', models.CharField(max_length=500, null=True)),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('imgae_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'custom_product_images',
            },
        ),
    ]
