# Generated by Django 3.0.1 on 2020-01-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_type_name', models.CharField(max_length=2500, null=True)),
            ],
            options={
                'db_table': 'artwork_types',
            },
        ),
        migrations.RemoveField(
            model_name='artworkcolor',
            name='artwork_color_image',
        ),
        migrations.AddField(
            model_name='artworkcolor',
            name='artwork_color_info',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkType'),
        ),
    ]
