# Generated by Django 3.0.1 on 2020-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20200115_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
